zuul:
  routes:
    serviceA:
      path: /serviceA
      url: forward:/services
  ratelimit:
    strategy: bucket
    enabled: true
    policies:
      serviceA:
        limit: 2
        interval: 1
        type:
          - url
spring:
  redis:
    host: 127.0.0.1
    port: 6379
