zuul:
  routes:
    serviceA:
      path: /serviceA
      url: forward:/services
  ratelimit:
    enabled: true
    policies:
      serviceA:
        strategy: bucket
        limit: 4
        interval: 60
        type:
          - url
spring:
  redis:
    host: 127.0.0.1
    port: 6379
