zuul:
  routes:
    serviceA:
      path: /serviceA
      url: forward:/services
  ratelimit:
    enabled: true
    policies:
      serviceA:
        limit: 10
        refresh-interval: 2
        type:
          - url
spring:
  redis:
    host: 127.0.0.1
    port: 6379
